In [27]:
import pandas as pd
import hashlib as hs
import numpy as np

housing = pd.read_csv('./housing./housing.csv')
housingTrain = './housing./trainset.csv'
housingTest = './housing./testset.csv'

def checkHash(value, ratio):
    return hs.md5(np.int64(value)).digest()[-1] < 256*ratio

def dissectData(data, ratio, identifier):
    idList = 0*len(data)
    trainDf = []
    testDf = []
    print(identifier)
    if type(identifier) is list:
        for item in identifier:
            idList = data[item] + idList
    testIdsList = idList.apply(lambda id_: checkHash(id_, ratio))
    testDf = data.loc[testIdsList]
    trainDf = data.loc[~testIdsList]
    return testDf, trainDf
    

def splitData():    
    indexList = ['longitude','latitude', 'households']
    testDf, trainDf = dissectData(housing, 0.2, indexList)
    testDf.to_csv(housingTest)
    trainDf.to_csv(housingTrain)
    return trainDf.describe()
    
splitData()

['longitude', 'latitude', 'households']

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,16781.000000,16781.000000,16781.000000,16781.000000,16614.000000,16781.000000,16781.000000,16781.000000,16781.000000
mean,-119.568154,35.624366,28.643704,2620.524939,534.536415,1418.068709,496.876646,3.886706,207764.025028
std,2.002260,2.134434,12.524966,2129.583907,413.832727,1118.963828,376.037625,1.901370,115729.423948
min,-124.300000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1453.000000,298.000000,788.000000,282.000000,2.573500,120700.000000
50%,-118.500000,34.250000,29.000000,2121.000000,432.000000,1165.000000,407.000000,3.550000,180900.000000
75%,-118.000000,37.710000,37.000000,3147.000000,647.000000,1724.000000,603.000000,4.770800,265900.000000
max,-114.490000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000